TestArd1/Models/ArdData.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestArd1.Models
{
    public class Rootobject
    {
        [JsonProperty("Podatki")]
        public List<Class1> Property1 { get; set; }
    }


    public partial class Class1
    {   
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [JsonProperty("device_id")]
        public string DeviceId { get; set; }

        [JsonProperty("raw")]
        public string Raw { get; set; }

        [JsonProperty("temperatura")]
        public decimal Temperatura { get; set; }
        [JsonProperty("time")]
        public System.DateTime Time { get; set; }

        [JsonProperty("vlaznost")]
        public decimal Vlaznost { get; set; }
    }

    public class NewArdContext : DbContext
    {
        public DbSet<Class1> Podatki { get; set; }
    }
}

TestArd1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestArd1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestArd1/Controllers/NewArdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestArd1.Models;

namespace TestArd1.Controllers
{
    public class NewArdController : Controller
    {
        // GET: NewArd
        public ActionResult Index()
        {
            var db = new NewArdContext();
            Rootobject rezultati = Bralnik.Beri();
            if (rezultati != null)
            {
                var podatki = from x in rezultati.Property1
                              orderby x.Time descending
                              select x;
                foreach (var y in podatki)
                {
                    y.Time = y.Time.AddHours(1);
                    y.Temperatura = y.Temperatura / 100;
                    y.Vlaznost = y.Vlaznost / 100;
                }

                return View(podatki);
            }
            else
            {
                List<Class1> kren = new List<Class1>();
                Class1 en = new Class1();
                en.Time = DateTime.Now;
                en.DeviceId = "fake1337";
                en.Raw = "a3jgu9d0";
                en.Temperatura = (decimal)20.20;
                en.Vlaznost = (decimal)40.40;
                kren.Add(en);

                return View(kren);
            }

        }

        public ActionResult Baza()
        {
            var db = new NewArdContext();
            var podatki1 = from x in db.Podatki
                           orderby x.Time descending
                           select x;
            foreach (var y in podatki1)
            {
                y.Time = y.Time.AddHours(1);
                y.Temperatura = y.Temperatura / 100;
                y.Vlaznost = y.Vlaznost / 100;
            }


            return View(podatki1);
        }
    }
}

TestArd1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestArd1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestArd1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TestArd1/Views/NewArd/Baza.cshtml
@model IEnumerable<TestArd1.Models.Class1>

@{
    ViewBag.Title = "Baza";
}

<h2>Baza Test</h2>
<h3>Beremo direktno iz baze</h3>

<div class="container">
    <table class="table table-hover">
        <tr>
            <th>
                ID
            </th>
            <th>
                Raw
            </th>
            <th>
                Datum in Čas
            </th>
            <th>
                Temperatura
            </th>
            <th>
                Vlaga
            </th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => x.DeviceId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Raw)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Temperatura)°C
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Vlaznost)%
                </td>
            </tr>
        }
    </table>

</div>

TestArd1/Views/NewArd/Index.cshtml
@model IEnumerable<TestArd1.Models.Class1>

@{
    ViewBag.Title = "Index";
}

<h2>Arduino Test</h2>
<h3>Beremo direktno iz http-request</h3>
<div class="container">
    <table class="table table-hover">
        <tr>
            <th>
                ID
            </th>
            <th>
                Raw
            </th>
            <th>
                Datum in Čas
            </th>
            <th>
                Temperatura
            </th>
            <th>
                Vlaga
            </th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => x.DeviceId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Raw)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Temperatura)°C
                </td>
                <td>
                    @Html.DisplayFor(modelItem => x.Vlaznost)%
                </td>
            </tr>
        }
    </table>

</div>

TestArd1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Http", "Index", "NewArd")</li>
                    <li>@Html.ActionLink("Baza", "Baza", "NewArd")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>